### ISSUE TITLE
Submit this PHP library to Packagist

### ISSUE THREAD

**Issue by jrockowitz** [coveo-labs/SDK-Push-PHP#2]
We would like to include this library in a Drupal module as a composer dependency. Can you please submit this library to Packagist.  

@see https://packagist.org/about
@see https://www.w3resource.com/php/composer/create-publish-and-use-your-first-composer-package.php

**Comment by AncaComanescu** [comment]
Here is the code snippet to include via composer.
```
{
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/coveo-labs/SDK-Push-PHP.git"
        }
    ],
    "require": {
        "coveo/sdkpushphp": "dev-master"        
    }
}
``` 
The name has to be lower case. Maybe the name should be `coveo/sdk-push-php`

 `require.coveo/SDKPushPHP is invalid, it should not contain uppercase characters. Please use coveo/sdkpushphp instead.`

**Comment by wnijmeijer** [comment]
Done: https://packagist.org/packages/coveo/sdkpushphp
