### ISSUE TITLE
Please widen the constraint on psr/log up to 3.0

### ISSUE THREAD

**Issue by kevinquillen** [coveo-labs/SDK-Push-PHP#25]
This package is currently not installable on applications that require psr/log:3.0.0.

**Comment by FatherShawn** [comment]
Comparing: [1.1.4...3.0.0](https://github.com/php-fig/log/compare/1.1.4...3.0.0)

**Comment by AncaComanescu** [comment]
@wnijmeijer  hello. This is Shawn Duncan we work on the lib for MSK. I approved latest Pr that will fix this issue. Can you please do another release? Shawn will continue to maintain the php drupal coveo module that uses this sdk.
