### ISSUE TITLE
AddSingleDocument() attempts to set undefined Document "Content" attribute.

### ISSUE THREAD

**Issue by stephen-w-keller** [coveo-labs/SDK-Push-PHP#29]
Version: 1.7.0
File: Push.php
Function: AddSingleDocument()

At line 1115 in a finally block, the AddSingleDocument() attempts to assign an empty string to the $p_CoveoDocument->Content attribute:

        try {
            if ($p_CoveoDocument->CompressedBinaryData !== '' || $p_CoveoDocument->Data !== '') {
                $this->UploadDocumentIfTooLarge($p_CoveoDocument);
            }
            $this->AddUpdateDocumentRequest($p_CoveoDocument, $orderingId);
        } finally {
            $p_CoveoDocument->Content = '';
        }

The Document class has no Content attribute in its specification and nothing in the Document logic appears to look for a Content attribute. The intent of that finally block is not clear. Perhaps it should read:

            $p_CoveoDocument->SetContentAndZLibCompress('');

Stph

**Comment by wnijmeijer** [comment]
thanks, makes sense. Normally this code will never execute
