### ISSUE TITLE
Reference to undeclared $attmpts variable at lines 617 and 670

### ISSUE THREAD

**Issue by stephen-w-keller** [coveo-labs/SDK-Push-PHP#30]
Version 1.7.0
File: Push.php
Functions: doPost(), doPut()

Lines 617 and 670 read as follows:

                echo "Attempt $attempts has failed. Waiting 3 seconds.\n";

The $attempts variable is never set or incremented. I suspect these lines should be converted to logger messages and should use the class $totalAttempts attribute, as follows: 

                $this->logger->debug("Attempt {$this->totalAttempts} has failed. Waiting 3 seconds.\n");

The retry logic in these two functions appears to be duplicated with only $url and $context variables differing. These duplicate blocks of code should probably be refactored to a private class function that takes the URI and context as parameters. Something like this for example:

    /**
     * Submit requests with up to five retries on error.
     * 
     * @param string $url
     *   Request URI
     * 
     * @param resource $context
     *   The request context with headers and any data
     * 
     * @return mixed
     *   The JSON response or FALSE  
     */
    private function sendRequestWithRetries($url, $context) {
        //Retry mechanism
        $this->totalAttempts = 0;
        do {
            $this->totalAttempts++;
            $result = file_get_contents(($url), false, $context);
            if (!$result) {
                $this->logger->error("Attempt {$this->totalAttempts} has failed. Waiting 3 seconds.\n");
                sleep(3);
            }
        } while (!$result && $this->totalAttempts < 5);
        return $result;
    }

Stph

**Comment by wnijmeijer** [comment]
Thanks man!
