### ISSUE TITLE
sendRequestWithRetries() should check for explicit false from file_get_contents() call.

### ISSUE THREAD

**Issue by stephen-w-keller** [coveo-labs/SDK-Push-PHP#31]
Version: 1.7.1
File: Push.php
Method: sendRequestWithRetries()

Some PUT|POST operations return null or empty strings. This is causing unnecessary retries at line 602 and 606:

    private function sendRequestWithRetries($url, $context)
    {
        //Retry mechanism
        $this->totalAttempts = 0;
        do {
            $this->totalAttempts++;
            $result = file_get_contents(($url), false, $context);
            if (!$result) {
                $this->logger->error("Attempt {$this->totalAttempts} has failed. Waiting 3 seconds.\n");
                sleep(3);
            }
        } while (!$result && $this->totalAttempts < 5);
        return $result;
    }

Shouldn't this be checking for an explicit false value? Something like this:

    private function sendRequestWithRetries($url, $context)
    {
        //Retry mechanism
        $this->totalAttempts = 0;
        do {
            $this->totalAttempts++;
            $result = file_get_contents(($url), false, $context);
            if (false === $result) {
                $this->logger->error("Attempt {$this->totalAttempts} has failed. Waiting 3 seconds.\n");
                sleep(3);
            }
        } while ((false === $result) && $this->totalAttempts < 5);
        return $result;
    }
    
Perhaps the last HTTP status message should also be evaluated for additional information:

    if ( false === $result ) {
        $error = error_get_last();
        $this->logger->error("Attempt {$this->totalAttempts} has failed: {$error['message']} at line {$error['line']}. Waiting 3 seconds.\n"
    }

I wonder if the "error" logs in the inner loop should be made "debug" logs. And single a "error" log entry be made at the end of the function if the result is explicitly false. My thinking here is that it's not an error in the batch until the retry limit has been reached.

Stph

**Comment by stephen-w-keller** [comment]
Here is the sendRequestWithRetries method as I have implemented in my local copy. I don't know if this the best way to do this, but it seems to work:

    private function sendRequestWithRetries($url, $context)
    {
        //Retry mechanism
        $this->totalAttempts = 0;
        $lastError = [];
        do {
            $this->totalAttempts++;
            $result = file_get_contents(($url), false, $context);
            if (false === $result) {
                $lastError = error_get_last();
                $this->logger->debug("Attempt {$this->totalAttempts} has failed: {$lastError['message']} at line {$lastError['line']} Waiting 3 seconds.\n");
                sleep(3);
            }
        } while (!$result && $this->totalAttempts < 5);
        if(false === $result) {
            $this->logger->error("Failed {$this->totalAttempts} retry attempts. Last message: {$lastError['message']} at line {$lastError['line']}\n");
        }
        return $result;
    }

Stph

**Comment by wnijmeijer** [comment]
Changed the code

**Comment by stephen-w-keller** [comment]
Thanks.
