### ISSUE TITLE
Push::totalSize is increased by documentSize, even when document is rejected because it is larger than the Push::GetSizeMaxRequest().

### ISSUE THREAD

**Issue by stephen-w-keller** [coveo-labs/SDK-Push-PHP#32]
Version: 1.7.2
File: Push.php
Method: Add()

The push total size is increased by incoming document size even when document size exceeds Push::GetSizeMaxRequest(). In this section from lines 1455 through 1465, shouldn't the line at 1457 to adjust the totalSize attribute be moved to follow the documentSize check?

        $documentSize = strlen($p_CoveoDocument->ToJson()) + 1;
        $size_max_req = $this->GetSizeMaxRequest();
        $this->totalSize += $documentSize;

        if ($documentSize > $size_max_req) {
            $this->logger->error("Document: " . $p_CoveoDocument->DocumentId . " can\'t be larger than " . $size_max_req . " bytes in size.");
            return false;
        } else {
            $this->logger->debug("Document: " . $p_CoveoDocument->DocumentId . " Currentsize: " . $this->totalSize . " vs max: " . $size_max_req);
        }

Stph

**Comment by wnijmeijer** [comment]
True, changed in both Add and AddJson
